### ISSUE TITLE
when build to upload avatar, taking to much ram memory and longer times to upload

### ISSUE THREAD

**Issue by Ozhy227** [bdunderscore/modular-avatar#1357] opened 2024-11-17 16:15 UTC
I have like around 100 GB project with many outfits, somehow when I upload an avatar it takes longer times and most of the time using all of my rams, I have been trying to identify the problem, and it is MA, when I don't use MA its upload faster and not using too much ram, other things I found even when I upload avatar in the new scene without any modular avatar setup in it, it still takes a long time, and I feel like the MA is emulate everything inside my Project, been have this problem a month and somehow the fix was I need to export it to a new project, but somehow it will have the issue again.

**Comment by Ozhy227** [comment] 2024-11-18 04:35
So just opne it and save it right, Here is the build, 

https://drive.google.com/file/d/1nhv5rZgECxDVaOLaDyJCwxnD6Bm3Oy4I/view?usp=sharing 

file to large to open upload it here

**Comment by bdunderscore** [comment] 2024-11-19 04:26
Looks like it's spending a lot of time loading assets:

![image](https://github.com/user-attachments/assets/60015f4a-0af0-40f7-8cb1-d97035bfeeb7)
![image](https://github.com/user-attachments/assets/8fb0e041-4f26-4da5-9c27-680b2a6b5dea)

Are you using a hard drive by any chance, instead of an SSD?

I also note some gaps that aren't currently covered by profiler timings that are using a bunch of time - please download the special build here: https://github.com/bdunderscore/ndmf/archive/refs/heads/prof-tmp.zip and extract the contents over the `Packages/nadena.dev.ndmf` folder in your project, then do another profiler run.

**Comment by bdunderscore** [comment] 2024-11-19 04:26
For what it's worth, I see opportunity to optimize some of this time here (in particular, we don't need to be loading all the texture references of all your materials...)

**Comment by Ozhy227** [comment] 2024-11-19 04:46
for the reference, i have another project that using modular avatar and in Hard drive and upload faster, and I have another one again in harddrive begin to experience slow build too

**Comment by Ozhy227** [comment] 2024-11-19 04:47
[Uploading Moe Profiller2.zip…]()
this is the profiller

**Comment by bdunderscore** [comment] 2024-11-19 14:11
Hmm. This trace looks very different from the previous one. In this one, processing took 4.4 seconds, most of which went into animator processing. The animator processing side of things should improve in 1.11.0.

In your original trace, however, most of the time went into asset loading from disk. I wonder if you have a lot of outfits on the same avatar, which aren't visible initially? I have some ideas on how to improve this, but it might take a bit to implement. Thanks for the profiler traces!

**Comment by Ozhy227** [comment] 2024-11-19 19:16
Oh ya it's a different avatar but the build time is the same, the first profiler has 4 outfits and accessories from another outfit that I stripped down when you said did I was using HDD, or not I think the reason it was using HDD was because the virtual memory was in HDD, every time I build it always take lie 29 gb ram of my 32 GB ram, if you want i will do another profiler and I already set the virtual memory on SSD for now.

**Comment by bdunderscore** [comment] 2024-11-26 03:12
According to the traces you posted, the avatars took very different amounts of processing time. Can you do a trace of the first one?

**Comment by Ozhy227** [comment] 2024-11-26 15:37
[Uploading Moe Profiller3.zip…]()
here I think this is the first one, I have been changing stuff like the virtual memory on my PC and maybe it will make different result

**Comment by Ozhy227** [comment] 2024-11-27 12:45
so i make the virtual memory only in my SSD and I got this error, when I usually put the virtual memory to my HDD its uploaded but taken so long like 30 - 1 hour time for uploading 

![image](https://github.com/user-attachments/assets/f62f501f-3097-44f0-82b6-fa61392c3eb7)

**Comment by bdunderscore** [comment] 2024-11-28 17:53
Oh wow. It looks like you've loaded some _60 gigabytes_ of texture data. I wonder if you've set your texture resolution too high, or accidentally disabled texture compression?

Try installing this: https://github.com/lilxyzw/lilAvatarUtils

Then open Window -> _lil _> lilAvatarUtils. Drag your avatar into the top slot, and take a screenshot of the result.

**Comment by bdunderscore** [comment] 2024-11-28 17:53
Also, what tools are you using other than Modular Avatar?

**Comment by bdunderscore** [comment] 2024-11-30 21:15
Okay, I think some of the changes in 1.10.11 might help with your performance issues. I can't help much with running out of memory - but I'd suggest reducing the number of textures or their resolution, because 1.36GB is a _lot_ of texture memory for a single avatar (and the build process is going to be painful if you're doing any texture processing with those...)

The other thing I'll recommend is moving your project to a different disk drive. Your `I:` drive has a slow response time which might be hurting things. Some examples:

![image](https://github.com/user-attachments/assets/c4cf7ac8-ad5c-4a98-be23-e62523c1c3cf)
![image](https://github.com/user-attachments/assets/e4c8cfb4-6613-4ea6-937e-df3acd55b5ee)

If I: is a hard drive, I'd suggest moving it to an SSD.

**Comment by Ozhy227** [comment] 2024-12-01 06:03
i already tried the new version, is still have the same chase, and the I drive is SSD too. thank you for your help, I might need making new project and split the asset

**Comment by Ozhy227** [comment] 2024-12-01 08:46
[Uploading Moe Profiller4.zip…]()
 this the profiller of the same avatar in new project, it is a lot faster to build and not use too much ram

**Comment by Ozhy227** [comment] 2024-12-01 08:53
https://drive.google.com/file/d/1cVh2WtYggvpaoD8tKsUQaeS4d0UgI4M5/view?usp=sharing

this is the new profiler of the same avatar in new project, it take a lot faster and less of ram, if you like to see it

**Comment by Gargrimm** [comment] 2024-12-02 18:17
![image](https://github.com/user-attachments/assets/e9e64be0-619c-4160-9c3c-66ebb7f9d8b7)

After checking the stacktrace I came across this part of the code. 
I added a "continue" to skip that part and I stopped having the same issues.
I logged all the assets that were being processed and they are almost all the files I have in the proyect regardless if they are being used by the avatar that I'm uploading.

NOTE: I use VRCFury + MA, and my workflow consist of having a single proyect with a base avatar and a prefab variants for each outfit, so all the assets are in the same proyect but are only used by some avatars.

**Comment by bdunderscore** [comment] 2024-12-03 01:33
Interesting - I'll take a look at whether this can be improved!

**Comment by bdunderscore** [comment] 2024-12-03 01:51
Thanks for the hint! I'll try to get this improved in the next NDMF release, and then we can check on perf again after that.

**Comment by Ozhy227** [comment] 2024-12-03 07:39
That is the same as my project! can you tell me how to do that??

**Comment by Gargrimm** [comment] 2024-12-03 11:26
> That is the same as my project! can you tell me how to do that??

![image](https://github.com/user-attachments/assets/5147b8ef-fbf6-4c64-897d-db80a1400062)
Edit the file "Packages\nadena.dev.ndmf\Editor\ChangeStream\ChangeNotifier.cs" and add the line: 
`continue; //Modified: skipping this fix my memory issue" like in the image`
Be careful, this is just a workarround for now,

**Comment by Ozhy227** [comment] 2024-12-03 14:20
thank you i will try

**Comment by bdunderscore** [comment] 2024-12-04 01:37
Please try upgrading to NDMF 1.6.2 which should fix the memory issue. Do you still have perf issues after NDMF 1.6.2?

**Comment by bdunderscore** [comment] 2024-12-04 01:37
And thanks @Gargrimm for pointing me to that!

**Comment by Ozhy227** [comment] 2024-12-04 02:26
I tested the 1.6.2 in 2 projects, the old project with 100 GB in HDD took 11 minutes to upload with RAM with around 6gb usage, and the other project had a smaller size in SSD taking 1 minute and around 4 GB RAM and I tested the last workaround in 1.6.1 too with the old project in HDD, it takes the same times around 11 minutes and 5.8 GB ram usage. it fixes the usual time when it took 1 hour with the old project in SSD before,

**Comment by bdunderscore** [comment] 2024-12-04 13:41
Glad to hear things have improved! I'll close this for now, please do report again if things seem unusually slow in the future.

**Closed by bdunderscore** 2024-12-04 13:41 UTC

**Comment by Ozhy227** [comment] 2025-01-19 12:26
i think the memory problem is back in 1.6.4?

**Comment by Gargrimm** [comment] 2026-07-23 12:36
This issue can be reproduced again in the newer version and it can be fixed the same way.

When uploading an avatar, if the proyect its too big, MA is trying to re-import everything in the poject and cosume all the RAM availabe.

**Comment by bdunderscore** [comment] 2026-07-23 13:07
@Gargrimm to confirm, you made substantially the same change and it fixed the issue?

If not please open a new issue for root causing

**Comment by Gargrimm** [comment] 2026-07-23 13:35
My bad, after further testing I notice the error seems to be with VRCFury.
With the following versions it works fine:
NDMF 1.14.1
MA 1.17.1
VRCFury 1.1362.0

But if I upgrade VRCFury to 1.1372.0 it crash in a similar way and similar tracelog.

**Comment by bdunderscore** [comment] 2026-07-23 15:45
Okay - sounds like an issue with VRCF, please report to them.
