### ISSUE TITLE
VRC Animator Play Audio Source Rename

### ISSUE THREAD

**Issue by BigAtomikku** [bdunderscore/modular-avatar#858] opened 2024-05-26 01:50 UTC
Currently Modular Avatar does not automatically rename the "source" field inside VRC Animator Play Audio when using Relative paths.

**Comment by bdunderscore** [comment] 2024-05-30 15:32
Duplicate of https://github.com/bdunderscore/modular-avatar/issues/783

**Closed by bdunderscore** 2024-05-30 15:32 UTC
